export enum EventsEnum {
  ORDER_BOOK_BUY_ITEM_CLICKED = "ORDER_BOOK_BUY_ITEM_CLICKED",
  ORDER_PLACED = "ORDER_PLACED",
  ORDER_BOOK_SELL_ITEM_CLICKED = "ORDER_BOOK_SELL_ITEM_CLICKED",
  CHANGE = "change",
  SUBMIT = "submit",
  ORDER_CLOSED = "ORDER_CLOSED",
  PAGE_CHANGED = "pageChanged",
  CLOSE = "close",
  NEED_SOCKETS_RECONNECT = "NEED_SOCKETS_RECONNECT",
}
