export enum IndicatorsEnum {
  MA = "MA",
  EMA = "EMA",
  WMA = "WMA",
  BOLL = "BOLL",
  VWAP = "VWAP",
  AVL = "AVL",
  TRIX = "TRIX",
  SAR = "SAR",
  VOL = "VOL",
  MACD = "MACD",
  RSI = "RSI",
  KDJ = "KDJ",
  OBV = "OBV",
  CCI = "CCI",
  STOCH_RSI = "StochRSI",
  WR = "WR",
  DMI = "DMI",
  MTM = "MTM",
  EMV = "EMV",
}
